#!/usr/bin/env python3
"""
Build system for CloudStream plugins.

Safety goals:
- Prefer .cs3 generated by Cloudstream task (:module:make)
- Reject invalid plugin packages (AAR-like) before publish
"""

import json
import os
import re
import shutil
import subprocess
import zipfile


PROVIDERS = {
    "MaxSeries": {"version": 279, "tvTypes": ["TvSeries", "Movie"]},
    "AnimesOnlineCC": {"version": 10, "tvTypes": ["Anime"]},
    "Vizer": {"version": 2, "tvTypes": ["TvSeries", "Movie"]},
    "NetCine": {"version": 2, "tvTypes": ["TvSeries", "Movie"]},
    "MegaFlix": {"version": 2, "tvTypes": ["TvSeries", "Movie"]},
    "PobreFlix": {"version": 2, "tvTypes": ["TvSeries", "Movie"]},
    "OverFlix": {"version": 2, "tvTypes": ["TvSeries", "Movie"]},
}


def get_module_version(module_name, fallback):
    gradle_file = os.path.join(module_name, "build.gradle.kts")
    if not os.path.exists(gradle_file):
        return fallback

    try:
        with open(gradle_file, "r", encoding="utf-8") as f:
            content = f.read()
        match = re.search(r"version\s*=\s*(\d+)", content)
        if match:
            return int(match.group(1))
    except Exception:
        pass

    return fallback


def is_valid_cloudstream_cs3(path):
    """
    Expected Cloudstream format:
    - zip file
    - contains manifest.json
    - contains classes.dex
    """
    if not os.path.exists(path):
        return False, "file does not exist"

    try:
        with zipfile.ZipFile(path, "r") as zf:
            entries = set(zf.namelist())
            if "manifest.json" not in entries:
                return False, "missing manifest.json"
            if "classes.dex" not in entries:
                return False, "missing classes.dex"
            if "classes.jar" in entries:
                return False, "contains classes.jar (AAR-like package)"
        return True, "ok"
    except zipfile.BadZipFile:
        return False, "not a valid zip"
    except Exception as e:
        return False, str(e)


def run_build():
    print("=== BUILD PLUGINS CLOUDSTREAM3 ===\n")
    print("Cleaning previous builds...")

    for provider in PROVIDERS.keys():
        build_dir = os.path.join(provider, "build")
        if os.path.exists(build_dir):
            shutil.rmtree(build_dir)
            print(f"  cleaned: {provider}")

    print("\nRunning Gradle build...")
    gradle_cmd = ["./gradlew", "assembleRelease", "-x", "test", "--no-daemon"]
    if os.name == "nt":
        gradle_cmd[0] = ".\\gradlew.bat"

    result = subprocess.run(gradle_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"BUILD ERROR:\n{result.stderr}")
        return False

    print("Build completed.")
    return True


def copy_packages_to_cs3():
    print("\n=== GENERATING .CS3 FILES ===")
    plugins = []

    for provider, info in PROVIDERS.items():
        output_cs3 = f"{provider}.cs3"
        source_cs3 = os.path.join(provider, "build", f"{provider}.cs3")
        source_aar_release = os.path.join(provider, "build", "outputs", "aar", f"{provider}-release.aar")
        source_aar_debug = os.path.join(provider, "build", "outputs", "aar", f"{provider}-debug.aar")

        if os.path.exists(source_cs3):
            shutil.copy(source_cs3, output_cs3)
            print(f"  OK {provider}.cs3 (from :{provider}:make output)")
        elif os.path.exists(source_aar_release):
            shutil.copy(source_aar_release, output_cs3)
            print(f"  WARN {provider}.cs3 copied from release AAR")
        elif os.path.exists(source_aar_debug):
            shutil.copy(source_aar_debug, output_cs3)
            print(f"  WARN {provider}.cs3 copied from debug AAR")
        else:
            print(f"  FAIL {provider}: no package found")
            continue

        valid, reason = is_valid_cloudstream_cs3(output_cs3)
        if not valid:
            print(f"  FAIL {provider}.cs3 invalid: {reason}")
            continue

        version = get_module_version(provider, info["version"])
        size = os.path.getsize(output_cs3)
        plugin = {
            "url": f"https://raw.githubusercontent.com/franciscoalro/TestPlugins/main/{output_cs3}",
            "status": 1,
            "version": version,
            "apiVersion": 1,
            "name": provider,
            "internalName": provider,
            "authors": ["franciscoalro"],
            "description": f"{provider} v{version}",
            "repositoryUrl": "https://github.com/franciscoalro/TestPlugins",
            "tvTypes": info["tvTypes"],
            "language": "pt-BR",
            "fileSize": size,
        }
        plugins.append(plugin)

    return plugins


def update_json_files(plugins):
    print("\n=== UPDATING JSON FILES ===")

    with open("plugins.json", "wb") as f:
        f.write(json.dumps(plugins, indent=2, ensure_ascii=False).encode("utf-8"))
        f.write(b"\n")
    print("  OK plugins.json")

    repo = {
        "name": "Franciscoalro Plugins",
        "description": "Repositorio de plugins para CloudStream3",
        "manifestVersion": 1,
        "pluginLists": [
            "https://raw.githubusercontent.com/franciscoalro/TestPlugins/main/plugins.json"
        ],
    }

    with open("repo.json", "wb") as f:
        f.write(json.dumps(repo, indent=2, ensure_ascii=False).encode("utf-8"))
        f.write(b"\n")
    print("  OK repo.json")


def verify_files():
    print("\n=== VERIFICATION ===")

    with open("plugins.json", "rb") as f:
        data = f.read()
        if data[0:3] == b"\xef\xbb\xbf":
            print("  FAIL plugins.json has BOM")
        else:
            print("  OK plugins.json without BOM")
        parsed = json.loads(data.decode("utf-8"))
        if isinstance(parsed, list):
            print(f"  OK plugins.json is list with {len(parsed)} plugins")
        else:
            print("  FAIL plugins.json is not a list")

    cs3_files = [f for f in os.listdir(".") if f.endswith(".cs3")]
    for cs3_file in cs3_files:
        valid, reason = is_valid_cloudstream_cs3(cs3_file)
        if valid:
            print(f"  OK {cs3_file} Cloudstream format")
        else:
            print(f"  FAIL {cs3_file}: {reason}")


def main():
    if not run_build():
        return 1

    plugins = copy_packages_to_cs3()
    if not plugins:
        print("\nFAIL: no valid Cloudstream .cs3 generated.")
        return 1

    update_json_files(plugins)
    verify_files()

    print("\n=== BUILD COMPLETED ===")
    print(f"Total plugins: {len(plugins)}")
    print("Repository URL:")
    print("  https://raw.githubusercontent.com/franciscoalro/TestPlugins/main/repo.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
