[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.cs3"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.jar"
  [headers.values]
    Content-Type = "application/java-archive"
    Cache-Control = "public, max-age=3600"