#!/bin/bash

# Script para configurar interceptação com Burp Suite

echo "🔧 Configuração do Burp Suite"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 PASSOS MANUAIS:"
echo ""
echo "1. Iniciar Burp Suite:"
echo "   $ burpsuite &"
echo ""
echo "2. Configurar Proxy:"
echo "   • Proxy → Options → Add"
echo "   • Bind to address: 127.0.0.1"
echo "   • Bind to port: 8080"
echo ""
echo "3. Configurar navegador:"
echo "   • Firefox: Preferences → Network Settings"
echo "   • Manual proxy: 127.0.0.1:8080"
echo "   • Use for all protocols"
echo ""
echo "4. Instalar certificado CA:"
echo "   • Abrir: http://burp"
echo "   • Download CA Certificate"
echo "   • Firefox: Preferences → Certificates → Import"
echo ""
echo "5. Interceptar PlayerEmbedAPI:"
echo "   • Proxy → Intercept → Intercept is on"
echo "   • Abrir: https://playerembedapi.link/?v=kBJLtxCD3"
echo "   • HTTP history → Procurar por:"
echo "     - lite.bundle.js"
echo "     - Requisições para /api/"
echo "     - Respostas com 'key', 'token', 'secret'"
echo ""
echo "6. Salvar requisições interessantes:"
echo "   • Right-click → Save item"
echo "   • Salvar em: $(pwd)/output/burp_*.txt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 O QUE PROCURAR:"
echo "  • Headers customizados (X-Key, X-Token, etc.)"
echo "  • Parâmetros de query (?key=, ?token=)"
echo "  • Respostas JSON com campos 'key', 'secret'"
echo "  • Cookies com informações de chave"
echo "  • WebSocket messages"
echo ""
echo "💡 DICA: Use o filtro no HTTP history:"
echo "   • Filter: Show only in-scope items"
echo "   • Target → Scope → Add: playerembedapi.link"
echo ""
