#!/bin/bash

# Guia de filtros Wireshark para análise

echo "🦈 Wireshark - Filtros para PlayerEmbedAPI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 SETUP:"
echo "1. Iniciar Wireshark:"
echo "   $ sudo wireshark &"
echo ""
echo "2. Selecionar interface de rede"
echo "   • eth0 (Ethernet)"
echo "   • wlan0 (WiFi)"
echo "   • any (todas)"
echo ""
echo "3. Iniciar captura"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 FILTROS ÚTEIS:"
echo ""
echo "# Filtrar por domínio"
echo "http.host contains \"playerembedapi.link\""
echo ""
echo "# Filtrar JavaScript"
echo "http.request.uri contains \".js\""
echo ""
echo "# Filtrar respostas com 'key'"
echo "http.response contains \"key\""
echo ""
echo "# Filtrar JSON"
echo "http.content_type contains \"json\""
echo ""
echo "# Filtrar WebSocket"
echo "websocket"
echo ""
echo "# Combinação completa"
echo "(http.host contains \"playerembedapi\" or http.host contains \"iamcdn\") and (http.request.uri contains \".js\" or http.response contains \"key\" or http.response contains \"crypto\")"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💾 EXPORTAR DADOS:"
echo "1. File → Export Objects → HTTP"
echo "2. Filtrar por: .js"
echo "3. Save All → output/wireshark_exports/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 ANÁLISE:"
echo "1. Follow → HTTP Stream (para ver requisição completa)"
echo "2. Procurar por:"
echo "   • Headers: X-Key, Authorization, X-Token"
echo "   • Query params: ?key=, ?token="
echo "   • Response body: {\"key\": \"...\"}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 DICA: Capturar em arquivo para análise posterior:"
echo "$ sudo tshark -i any -w output/capture.pcap -f \"host playerembedapi.link\""
echo ""
echo "Analisar depois:"
echo "$ tshark -r output/capture.pcap -Y \"http.request.uri contains .js\""
echo ""
